### ISSUE TITLE
Rename repository to 'aws-event-sources'

### ISSUE THREAD

**Issue by antoineco** [triggermesh/knative-lambda-sources#51]
In a attempt to consolidate the naming and grouping of our event sources, we should rename this repository from `knative-lambda-sources` to `aws-event-sources`.

Steps:
1. Rename the repo in GitHub settings
1. Update packages imports
1. Update CI

**Comment by sebgoa** [comment]
one caveat here, we did some marketing around KLASS: Knative Lambda SourceS ...

we should spend 5 minutes thinking about this...see the logo in the README

**Comment by antoineco** [comment]
Replaced by #56
